---

- import_role:
    name: elastic

- name: install metricbeat
  become: yes
  yum:
    name: metricbeat-{{ version }}
    state: present
    update_cache: yes
  notify: restart metricbeat

- name: copy metricbeat.yml /etc/metricbeat/metricbeat.yml
  become: yes
  template:
    src: templates/metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
  notify: restart metricbeat

- name: flush all handlers
  meta: flush_handlers

- name: metricbeat modules enable system
  become: yes
  command: metricbeat modules enable system

- name: metricbeat modules enable beat-xpack
  become: yes
  command: metricbeat modules enable beat-xpack

- name: setup metricbeat
  become: yes
  shell: metricbeat setup  -E 'setup.kibana.host={{ groups['elk'][0] }}:5601' && touch /tmp/metricbeat.setup
  args:
    creates: /tmp/metricbeat.setup
