---

- name: add grafana repo
  become: yes
  yum_repository:
    name: grafana
    description: Grafana repository
    file: grafana
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: true
    gpgkey: https://packages.grafana.com/gpg.key
    enabled: true

- name: install grafana
  become: yes
  yum:
    name: grafana-{{ version }}
    state: installed
  notify: "restart grafana-server"

- name: setup grafana
  become: yes
  template:
    src: templates/grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: "restart grafana-server"

- name: setup datasources
  become: yes
  template:
    src: templates/datasources/{{ item }}.yml.j2
    dest: /etc/grafana/provisioning/datasources/{{ item }}.yml
  with_items:
    - prometheus
  notify: "restart grafana-server"

- name: setup dashboards
  become: yes
  template:
    src: templates/dashboards/dashboards.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboards.yml
  notify: "restart grafana-server"

- name: create {{ grafana_dashboards }}
  become: yes
  file:
    path: "{{ grafana_dashboards }}"
    state: directory
    mode: 0755
  notify: "restart grafana-server"

- name: copy dashboards
  become: yes
  copy:
    src: dashboards/{{ item }}.json
    dest: "{{ grafana_dashboards }}/{{ item }}.json"
  with_items:
    - kafka
