- hosts: elk
  remote_user: vagrant
  serial: 100%
  roles:
    - java
    - elasticsearch
    - kibana  
    - metricbeat

- hosts: prometheus
  remote_user: vagrant
  serial: 100%
  roles:
    - metricbeat
    - prometheus

- hosts: grafana
  remote_user: vagrant
  serial: 100%
  roles:
    - grafana

- hosts: kafka
  remote_user: vagrant
  serial: 33%
  roles:
    - java
    - filebeat
    - metricbeat
    - secure
    - kafka

- hosts: kafka
  remote_user: vagrant
  serial: 33%
  tasks:
    - name: restart
      become: yes
      systemd:
        enabled: yes
        state: restarted
        name: kafka
        daemon_reload: yes