---

- import_role:
    name: elastic

- name: install kibana
  become: yes
  yum:
    name: kibana-{{ version }}
    state: present
    update_cache: yes
  notify: "restart kibana"

- name: copy /etc/kibana/kibana.yml
  become: yes
  template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: "restart kibana"

- name: run handlers
  meta: flush_handlers

- name: wait until kibana api is reachable
  uri:
    url: http://{{ inventory_hostname }}:5601/api/status
    status_code: "200"
  retries: 5
  delay: 5
  register: result
  until: result.status == 200

- name: set default index pattern
  uri:
    url: "http://{{ inventory_hostname }}:5601/api/kibana/settings/defaultIndex"
    method: POST
    headers:
      kbn-xsrf: true
    body_format: json
    body: "{ \"value\": \"metricbeat-*\"  }"
